### ISSUE TITLE
Failure when using context manager

### ISSUE THREAD

**Issue by pritamdamania87** [Lightning-AI/lightning-thunder#426] opened 2024-05-16 17:24 UTC
## 🐛 Bug

Running into the following issue when using a context manager.

```
AttributeError: The torch language context has no method clone
```

### To Reproduce

```
import contextlib
import thunder
import torch

class MyModule(torch.nn.Module):
    def forward(self, tensor):
        context = contextlib.nullcontext

        with context():
            return tensor.clone()


m = thunder.jit(MyModule())
m(torch.rand(10, 10, device="cuda"))
```

Only using `clone` also fails:

```
import contextlib
import thunder
import torch

def forward(tensor):
  return tensor.clone()


compiled = thunder.jit(forward)
compiled(torch.rand(10, 10, device="cuda"))
```

### Environment

- PyTorch Version (e.g., 1.0): 2.4.0.dev20240514+cu121
- OS (e.g., Linux): Linux
- How you installed PyTorch (`conda`, `pip`, source): pip
- Build command you used (if compiling from source):
- Python version: 3.11
- CUDA/cuDNN version: 12.2
- GPU models and configuration: H100
- Any other relevant information:

**Comment by tfogal** [comment] 2024-05-16 18:39
triage: duplicate of #342?

**Closed** 2024-05-16 19:00 UTC
Labels: bug
