### ISSUE TITLE
ThunderFX: Dump each FX graph to a standalone file

### ISSUE THREAD

**Issue by kiya00** [Lightning-AI/lightning-thunder#1332] opened 2024-10-21 09:03 UTC
## 🚀 Feature

Be able to dump each FX graph to a standalone file that executes the FX graph using multiple requested executors

### Motivation

Debuggability improvement. Pulling repros out of dependencies is important for dev velocity.

### Additional context

cc @apaz-cli @tfogal @mruberry @IvanYashchuk

**Comment by kiya00** [comment] 2024-10-21 09:09
Hi @mruberry @tfogal , could you provide some more context on this feature? Currently in the ThunderFX path, each split `GraphModule` is stored in the `ThunderCompiler.subgraph_info`, is this feature intended to save the original code of each `GraphModule` in a separate python file?

**Comment by mruberry** [comment] 2024-10-21 15:09
Hey @kiya00!

It'd be nice to generate actual Python files that contained the FX graph as a Python function, generated synthetic inputs to call that function (based on what it was last called with), and have the calls we used to compile the operation (like if we call thunder.jit, what kwargs, if any, were passed to it). That way the file can be executed to replay the computation.

It would also be great if the file had comments describing the original FX graph and the versions of relevant modules (nvFuser, torch, thunder, ...) and models of relevant hardware (gpu model).

Does that make sense? Maybe we can work through an example together if that'd be helpful.

**Comment by tfogal** [comment] 2024-10-21 15:49
Hi, I think this is a duplicate of #1082; closing as dup in favor of that older issue.

To be clearer, we were talking about upstreaming https://github.com/tfogal/NeMo/blob/a0c711deae6c6f7342662795425684a342f95b8d/examples/multimodal/multimodal_llm/neva/neva_pretrain.py#L164 s.t. it happens inside thunder.

Now that you've got something that runs things w/ different executors already, it's plausible that we could have it hook into that infra.

**Closed by tfogal** 2024-10-21 15:49 UTC
Labels: enhancement, debugging, dynamo+thunder
