### ISSUE TITLE
Benchmark `test_llama_2_7b_grad` gets OOM on A100 and H100

### ISSUE THREAD

**Issue by xwang233** [Lightning-AI/lightning-thunder#189] opened 2024-04-15 22:13 UTC
## 🐛 Bug

Benchmark `test_llama_2_7b_grad` gets OOM on A100 and H100

### To Reproduce

```bash
pytest thunder/benchmarks/targets.py -vs thunder/benchmarks/targets.py::test_llama_2_7b_grad[thunder]
```

#### Code sample

Below gets OOM on A100 40 GB
- thunder.benchmarks.targets.test_llama_2_7b_grad[thunder+cudnn]
- thunder.benchmarks.targets.test_llama_2_7b_grad[torch.compile]
- thunder.benchmarks.targets.test_llama_2_7b_grad[torch]
- thunder.benchmarks.targets.test_llama_2_7b_grad[thunder+nvfuser+torch.compile]
- thunder.benchmarks.targets.test_llama_2_7b_grad[thunder]

Below gets OOM on H100 80 GB
- thunder.benchmarks.targets.test_llama_2_7b_grad[thunder]
- thunder.benchmarks.targets.test_llama_2_7b_grad[thunder+cudnn]
 - thunder.benchmarks.targets.test_llama_2_7b_grad[thunder+nvfuser+torch.compile]

### Expected behavior

no oom

### Environment

- PyTorch Version (e.g., 1.0): 2.4.0a0+gitf5331aa
- Thunder: 139cc2246b87f3e58d80b13897286a61d55826d8
- Internal image: pjnl-20240415

### Additional context

N/A

cc @tfogal @IvanYashchuk

**Comment by tfogal** [comment] 2024-04-15 22:20
Thanks @xwang233 !

To be clear, Xiao: is the OOM behavior new (i.e. this worked at some point in the past)? Or we've never been able to run these on single-GPU?

Assigning to @IvanYashchuk; can you triage+assign, or just assign to someone?

**Comment by xwang233** [comment] 2024-04-15 22:25
The earliest failure I can find in database was 02/07/24, when we added those `-k thunder` benchmarks in CI. There were some infra issues that made it a bit hard to track and report old failures, but those are now fixed.

**Comment by IvanYashchuk** [comment] 2024-04-19 11:50
Running FSDP Llama 2 7B with batch=2 also goes OOM on the main and I suspect the root cause is the same for other reported problems https://github.com/Lightning-AI/lightning-thunder/issues/216.
Bisection tells that the problem was introduced in https://github.com/Lightning-AI/lightning-thunder/pull/115

**Comment by IvanYashchuk** [comment] 2024-04-22 10:02
Thank you, Xiao, for reporting this! The problem is fixed in https://github.com/Lightning-AI/lightning-thunder/pull/239.

**Closed by IvanYashchuk** 2024-04-22 10:02 UTC
Labels: bug
