### ISSUE TITLE
Networkx.exception.NetworkXUnbounded for Gemma-2-27b

### ISSUE THREAD

**Issue by mpatel31415** [Lightning-AI/lightning-thunder#1295] opened 2024-10-14 14:09 UTC
When running Gemma-2-27b with Thunder we get an error:

>  Networkx.exception.NetworkXUnbounded: Infinite capacity path, flow unbounded above.

The error can be recreated for 1 node with 8 gpus as well, but then even for torch.compile we get OOM error (with 2 nodes we can run this model with torch.compile).

## 🐛 Bug

Full traceback: 

> 4: Traceback (most recent call last):
 4:   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
 4:     return _run_code(code, main_globals, None,
 4:   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
 4:     exec(code, run_globals)
 4:   File "/usr/local/lib/python3.10/dist-packages/mixology_logs/execution/main.py", line 89, in <module>
 4:     CLI(main)
 4:   File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 96, in CLI
 4:     return _run_component(components, init)
 4:   File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 204, in _run_component
 4:     return component(**cfg)
 4:   File "/usr/local/lib/python3.10/dist-packages/mixology_logs/execution/main.py", line 69, in main
 4:     raise Exception(
 4: Exception: Unexpected error occurred for {'--micro_batch_size': 1} due to [rank4]: Traceback (most recent call last):
 4: [rank4]:   File "/workspace/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py", line 949, in <module>
 4: [rank4]:     CLI(benchmark_main)
 4: [rank4]:   File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 96, in CLI
 4: [rank4]:     return _run_component(components, init)
 4: [rank4]:   File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 204, in _run_component
 4: [rank4]:     return component(**cfg)
 4: [rank4]:   File "/workspace/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py", line 861, in benchmark_main
 4: [rank4]:     benchmark.train()
 4: [rank4]:   File "/workspace/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py", line 742, in train
 4: [rank4]:     logits = self.model(input_ids)
 4: [rank4]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
 4: [rank4]:     return self._call_impl(*args, **kwargs)
 4: [rank4]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
 4: [rank4]:     return forward_call(*args, **kwargs)
 4: [rank4]:   File "/opt/pytorch/lightning-thunder/thunder/core/module.py", line 80, in forward
 4: [rank4]:     res = self._forward_fn(*args, **kwargs)
 4: [rank4]:   File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 737, in fn_
 4: [rank4]:     cache_entry, inps, pro_to_epi = get_computation_and_inputs(*args, **kwargs)
 4: [rank4]:   File "/opt/pytorch/lightning-thunder/thunder/core/langctxs.py", line 136, in _fn
 4: [rank4]:     result = fn(*args, **kwargs)
 4: [rank4]:   File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 232, in cache_info_wrapper
 4: [rank4]:     res = fn(*args, **kwargs)
 4: [rank4]:   File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 650, in get_computation_and_inputs
 4: [rank4]:     computation_trc, backward_trc = split_forward_backward(computation_trc, cd, cs, *inps)
 4: [rank4]:   File "/opt/pytorch/lightning-thunder/thunder/executors/torch_autograd.py", line 231, in split_forward_backward
 4: [rank4]:     bw_extrace = transform_for_execution(
 4: [rank4]:   File "/opt/pytorch/lightning-thunder/thunder/executors/passes.py", line 160, in transform_for_execution
 4: [rank4]:     extrace = ex.fusion_pass(extrace)
 4: [rank4]:   File "/opt/pytorch/lightning-thunder/thunder/executors/nvfuserex_impl.py", line 900, in fusion_pass
 4: [rank4]:     fusedtrace = rematerialize(fusedtrace)
 4: [rank4]:   File "/opt/pytorch/lightning-thunder/thunder/core/rematerialization.py", line 544, in rematerialize
 4: [rank4]:     cut = find_cut(external_producer_outputs, current_producer, current_consumer)
 4: [rank4]:   File "/opt/pytorch/lightning-thunder/thunder/core/rematerialization.py", line 377, in find_cut
 4: [rank4]:     _, (reachable, non_reachable) = nx.minimum_cut(g, "source", "sink")
 4: [rank4]:   File "<class 'networkx.utils.decorators.argmap'> compilation 4", line 3, in argmap_minimum_cut_1
 4: [rank4]:   File "/usr/local/lib/python3.10/dist-packages/networkx/utils/backends.py", line 948, in __call__
 4: [rank4]:     return self.orig_func(*args, **kwargs)
 4: [rank4]:   File "/usr/local/lib/python3.10/dist-packages/networkx/algorithms/flow/maxflow.py", line [454](https://gitlab-master.nvidia.com/dl/jet/ci/-/jobs/115964149#L454), in minimum_cut
 4: [rank4]:     R = flow_func(flowG, _s, _t, capacity=capacity, value_only=True, **kwargs)
 4: [rank4]:   File "<class 'networkx.utils.decorators.argmap'> compilation 8", line 3, in argmap_preflow_push_5
 4: [rank4]:   File "/usr/local/lib/python3.10/dist-packages/networkx/utils/backends.py", line 948, in __call__
 4: [rank4]:     return self.orig_func(*args, **kwargs)
 4: [rank4]:   File "/usr/local/lib/python3.10/dist-packages/networkx/algorithms/flow/preflowpush.py", line 422, in preflow_push
 4: [rank4]:     R = preflow_push_impl(G, s, t, capacity, residual, global_relabel_freq, value_only)
 4: [rank4]:   File "/usr/local/lib/python3.10/dist-packages/networkx/algorithms/flow/preflowpush.py", line 41, in preflow_push_impl
 4: [rank4]:     detect_unboundedness(R, s, t)
 4: [rank4]:   File "<class 'networkx.utils.decorators.argmap'> compilation 16", line 3, in argmap_detect_unboundedness_13
 4: [rank4]:   File "/usr/local/lib/python3.10/dist-packages/networkx/utils/backends.py", line 948, in __call__
 4: [rank4]:     return self.orig_func(*args, **kwargs)
 4: [rank4]:   File "/usr/local/lib/python3.10/dist-packages/networkx/algorithms/flow/utils.py", line 173, in detect_unboundedness
 4: [rank4]:     raise nx.NetworkXUnbounded(
 4: [rank4]: networkx.exception.NetworkXUnbounded: Infinite capacity path, flow unbounded above.

### To Reproduce

Please use:
2 node(s), each with 8 GPUs.
Image "INTERNAL_IMAGE:pjnl-20241011"
Training script:
NVFUSER_DISABLE=multidevice python /opt/pytorch/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py \
    --model_name Gemma-2-27b \
    --distributed_mode fsdp \
    --shard_mode zero2 \
    --compile thunder \
    --checkpoint_activations True \
    --low_precision_mode none  \
    --micro_batch_size 1

### Expected behavior
We should not see this error.

### Environment

system.device_product_name                      DGXH100
system.gpu_driver_version                    535.129.03
libraries.cuda                               12.6.2.004
libraries.pip.lightning               2.4.0.dev20240728
libraries.pip.lightning-thunder              0.2.0.dev0
libraries.pip.lightning-utilities                0.11.7
libraries.pip.litgpt                             0.4.11
libraries.pip.nvfuser                 0.2.15+gitf3a2087
libraries.pip.pytorch-lightning                   2.4.0
libraries.pip.torch                  2.6.0a0+git4e89977
libraries.pip.torchmetrics                        1.4.3
libraries.pip.torchvision              0.19.0a0+d23a6e1

**Comment by IvanYashchuk** [comment] 2024-10-15 15:43
We have recently switched from igraph to networkx to compute min-cut for fusion rematerialization.

@kiya00, could you please check if there's a simpler 1 GPU reproducer with a smaller number of layers and investigate what are the problematic producers and consumers?

**Comment by kiya00** [comment] 2024-10-16 09:50
`python thunder/benchmarks/benchmark_litgpt.py --model_name Gemma-2-27b --compile thunder --checkpoint_activations True --low_precision_mode none --micro_batch_size 1 --n_layers=2` failed with the same error `networkx.exception.NetworkXUnbounded: Infinite capacity path, flow unbounded above.`

**Comment by IvanYashchuk** [comment] 2024-10-16 13:55
There may be a bug in the graph that we set up to compute the min-cut. The visual representation of the graph together with dumps of producer-consumer fusions would be a good start for debugging.

**Comment by kiya00** [comment] 2024-10-18 08:04
This is the same issue as https://github.com/Lightning-AI/lightning-thunder/issues/1232, and the reason is the same as @riccardofelluga 's [analysis](https://github.com/Lightning-AI/lightning-thunder/issues/1232#issuecomment-2419824493)
And in the cases `networkx.minimal_cut` fails, although the `cut.cut` in `cut=igraph.min_cut()` contains values, the `cut.value` is always `nan`

**Comment by riccardofelluga** [comment] 2024-10-18 08:06
Yes it is I was about to write a message here 😄 It's about rematerialization and it's the same error as #1232. Can be better debugged by setting the capacity of the edges to max float instead of inf. With that I was able to single out the error.

**Comment by IvanYashchuk** [comment] 2024-10-18 08:22
The error message has changed due to switching to a different library but the root cause remains the same. Closing this issue as the duplicate of https://github.com/Lightning-AI/lightning-thunder/issues/1232.

**Closed by IvanYashchuk** 2024-10-18 08:22 UTC
Labels: rematerialization, mixology
