### ISSUE TITLE
Mixtral model from LitGPT fails with `torch.where` error when using Thunder.

### ISSUE THREAD

**Issue by parthmannan** [Lightning-AI/lightning-thunder#698] opened 2024-07-03 06:21 UTC
## 🐛 Bug

The Mixtral model errors out with
```
An error occurred: NotImplementedError – torch.where() does not support only specifying a condition
```

Interestingly, the error does not provide any traceback but I have tested a smaller version of the model does work with Eager and Torch.Compile without errors.

### To Reproduce
Reproducible command -
```
torchrun --nproc-per-node=8 thunder/benchmarks/benchmark_litgpt.py --model_name Mixtral-8x7B-v0.1 --compile thunder_inductor_cat_cudnn --distributed_mode fsdp --shard_mode zero3
```

### Expected behavior
Mixtral model should work with Thunder and the benchmarking script.

### Additional context
This needs the PR #697 merged to test.

**Comment by IvanYashchuk** [comment] 2024-07-04 15:59
Thank you for creating the issue!
It's a known problem that Mixtral doesn't work.
There's a tracking issue for the network support https://github.com/Lightning-AI/lightning-thunder/issues/194 and a specific issue about `torch.where(condition)` overload https://github.com/Lightning-AI/lightning-thunder/issues/124. I will close this issue as a duplicate of those two.

This model works without errors with torch.compile because I think Dynamo creates a graph break around this operation and executes it eagerly.

**Closed by IvanYashchuk** 2024-07-04 15:59 UTC
