### ISSUE TITLE
ThunderFX is significantly slower than 2 weeks ago for 3 models

### ISSUE THREAD

**Issue by mpatel31415** [Lightning-AI/lightning-thunder#1428] opened 2024-11-12 16:04 UTC
## 🐛 Bug

Here are recently found regressions:

![image](https://github.com/user-attachments/assets/1ac968f7-b988-40f3-bb30-72b2efd303e2)

### To Reproduce

All parameters to benchmark_litgpt.py  are visible in the attached image. 

### Environment
system.device_product_name                      DGXH100
system.gpu_driver_version                    535.129.03
libraries.cuda                              12.6.98.001
libraries.pip.lightning               2.4.0.dev20240728
libraries.pip.lightning-thunder              0.2.0.dev0
libraries.pip.lightning-utilities                0.11.8
libraries.pip.litgpt                             0.4.11
libraries.pip.nvfuser                 0.2.22+gitba4f7d4
libraries.pip.pytorch-lightning                   2.4.0
libraries.pip.torch                  2.6.0a0+gita9b4989
libraries.pip.torchao                             0.6.1
libraries.pip.torchmetrics                        1.5.1
libraries.pip.torchvision              0.19.0a0+d23a6e1

**Comment by IvanYashchuk** [comment] 2024-11-12 16:57
The difference seems to be due to regression in the batch size used (2 -> 1). This could be related to the switch to the "block" bucketing mode instead of "none". There was an increase in memory usage for other models resulting in OOM and here it seems it resulted in a smaller batch size that works. @kiya00, could you please take a look at this regression and find out what has caused this?

**Comment by kiya00** [comment] 2024-11-18 15:18
> The difference seems to be due to regression in the batch size used (2 -> 1). This could be related to the switch to the "block" bucketing mode instead of "none".

Hi @IvanYashchuk  @mpatel31415  I tested the following model with the parameters used 2 weeks ago(20241025) in the new container 20241114, and the difference of "average iter time" is less than +/-1%. So I think in this case the regression comes from the change in bucketing mode(none->block) and the change in batch size associated with it.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/wayan/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/wayan/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">


  | nodes | GPUs | low precision | global bs | micro bs | checkpointing |   | bucketing mode | Average iter time(ms) 20241114 | Average iter time(ms) 20241025 | difference(%)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
falcon-40b | 4 | 8 | none | 64 | 2 | FALSE | zero3 | none | 86768.01 | 87014.29 | -0.28303
vicuna-33b-v1.3 | 2 | 8 | fp8-delayed-te | 32 | 2 | FALSE | zero3 | none | 65192.29 | 65251.95 | -0.09143
platypus-30B | 2 | 8 | fp8-delayed-te | 32 | 2 | FALSE | zero3 | none | 65349.34 | 65298.18 | 0.078348
pythia-12b | 2 | 8 | none | 80 | 5 | FALSE | zero3 | none | 23789.64 | 23827.29 | -0.15801
falcon-7b | 2 | 8 | none | 96 | 6 | FALSE | zero2 | none | 9649.5 | 9654.05 | -0.04713
pythia-12b | 1 | 8 | none | 24 | 3 | FALSE | zero2 | none | 885.55 | 886.17 | -0.06996
falcon-7b | 1 | 8 | none | 56 | 7 | FALSE | zero3 | none | 1195.17 | 1195.06 | 0.009205
dolly-v2-3b | 2 | 8 | none | 160 | 10 | FALSE | zero2 | none | 3828.87 | 3826.06 | 0.073444



</body>

</html>

**Comment by IvanYashchuk** [comment] 2024-11-20 13:55
Thank you for checking this, Yan!

@mpatel31415, so the regression is caused by transitioning to the "block" bucketing mode by default (as recommended by PyTorch). You've observed similar results for Eager that "block" vs "none" is not a clear choice performance-wise for all models. The mystery is solved and I'll close the issue. I think it's fine to continue testing performance only for the "block" mode, it's also the default way of applying FSDP2.

**Closed by IvanYashchuk** 2024-11-20 13:55 UTC
Labels: mixology
