### ISSUE TITLE
Devices were expected to be the same, but got ... when Benchmarking Gemma-7b with Micro Batch Size 1

### ISSUE THREAD

**Issue by mjmikulski** [Lightning-AI/lightning-thunder#941] opened 2024-08-08 09:42 UTC
## 🐛 Bug

When using `benchmark_litgpt` Following error occurs:

```
Exception: Unexpected error occurred for {\'--micro_batch_size\': 1} due to [W803 20:39:12.165884696 socket.cpp:752] [c10d] The client socket has failed to connect to [eos0157.eos.clusters.nvidia.com]:59504 (errno: 22 - Invalid argument).
[rank4]: RuntimeError: Devices were expected to be the same, but got devices thunder.devices.Device(type=\'cuda\', index=4) and thunder.devices.Device(type=\'cpu\')!
```

### To Reproduce

Start interactive job on a cluster:

```
srun -A YOUR_SLURM_ACCOUNT -J YOUR_SLURM_ACCOUNT-thunder.lit-gpt -N1 -p batch --container-image=INTERNAL_IMAGE:pjnl-20240801 --pty bash
```

Then execute:

```
torchrun --standalone --max-restarts=0 --no-python --nproc-per-node=8 python /opt/pytorch/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py \
    --model_name Gemma-7b \
    --distributed_mode fsdp \
    --shard_mode zero2 \
    --compile thunder_cudnn \
    --checkpoint_activations False \
    --low_precision_mode fp8-delayed-te \
    --save_logs_for_all_batches True \
    --micro_batch_size 1
```

### Expected Behavior
When running the benchmark for the Gemma-7b model with the specified configurations, the benchmarking scripts should successfully execute without any errors. 

### Environment

```
system.device_product_name                      DGXH100
system.gpu_driver_version                    535.129.03
libraries.cuda                               12.6.0.021
libraries.pip.lightning               2.4.0.dev20240728
libraries.pip.lightning-thunder              0.2.0.dev0
libraries.pip.lightning-utilities                0.11.6
libraries.pip.litgpt                              0.4.7
libraries.pip.nvfuser                  0.2.8+git671171f
libraries.pip.pytorch-lightning                   2.3.3
libraries.pip.torch                  2.5.0a0+gita94e507
libraries.pip.torchmetrics                  1.4.0.post0
libraries.pip.torchvision              0.19.0a0+d23a6e1
```

### Additional context

Comment: seems like a thunder bug somewhere; something is somehow ending up on the CPU even though it shouldn’t be.

**Comment by kiya00** [comment] 2024-08-08 14:01
It seems I didn't reproduce this error on H100 80GB, instead I got OOM (I removed the `--save_logs_for_all_batches True`)
```
container: pjnl-20240801
lightning-thunder      0.2.0.dev0          /opt/pytorch/lightning-thunder
nvfuser                0.2.8+git671171f    /opt/pytorch/nvfuser
```
```
root@803c226ee238:/opt/pytorch/lightning-thunder# torchrun --standalone --max-restarts=0 --no-python --nproc-per-node=8 python /opt/pytorch/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py     --model_name Gemma-7b     --distributed_mode fsdp     --shard_mode zero2     --compile thunder_cudnn     --checkpoint_activations False     --low_precision_mode fp8-delayed-te     --micro_batch_size 1
W0808 13:28:05.563000 931 torch/distributed/run.py:793]
W0808 13:28:05.563000 931 torch/distributed/run.py:793] *****************************************
W0808 13:28:05.563000 931 torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
W0808 13:28:05.563000 931 torch/distributed/run.py:793] *****************************************
Loading model with {'name': 'Gemma-7b', 'hf_config': {'org': 'google', 'name': 'gemma-7b'}, 'scale_embeddings': True, 'block_size': 4096, 'vocab_size': 256000, 'padding_multiple': 64, 'padded_vocab_size': 256000, 'n_layer': 28, 'n_head': 16, 'head_size': 256, 'n_embd': 3072, 'rotary_percentage': 1.0, 'parallel_residual': False, 'bias': False, 'lm_head_bias': False, 'n_query_groups': 16, 'shared_attention_norm': False, 'norm_class_name': 'RMSNorm', 'norm_eps': 1e-05, 'mlp_class_name': 'GemmaMLP', 'gelu_approximate': 'tanh', 'intermediate_size': 24576, 'rope_condense_ratio': 1, 'rope_base': 10000, 'n_expert': 0, 'n_expert_per_token': 0, 'rope_n_elem': 256}
Time to instantiate model: 0.02 seconds.
...
[rank6]: Traceback (most recent call last):
[rank6]:   File "/opt/pytorch/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py", line 628, in <module>
[rank6]:     CLI(benchmark_main)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 96, in CLI
[rank6]:     return _run_component(components, init)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 204, in _run_component
[rank6]:     return component(**cfg)
[rank6]:   File "/opt/pytorch/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py", line 583, in benchmark_main
[rank6]:     benchmark.train()
[rank6]:   File "/opt/pytorch/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py", line 495, in train
[rank6]:     loss.backward()
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 522, in backward
[rank6]:     torch.autograd.backward(
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 346, in backward
[rank6]:     _engine_run_backward(
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/autograd/graph.py", line 812, in _engine_run_backward
[rank6]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank6]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.95 GiB. GPU 6 has a total capacity of 79.10 GiB of which 1.03 GiB is free. Process 2592558 has 78.06 GiB memory in use. Of the allocated memory 75.47 GiB is allocated by PyTorch, and 674.49 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
...
```

**Comment by mjmikulski** [comment] 2024-08-09 08:20
Thank you for the answer. 
How many GPUs did you use? 
AFAIK this was executed on a single node with 8 GPUs (H100).

**Comment by kiya00** [comment] 2024-08-09 11:50
Yes, I used 1 node with 8 H100(80G). Has anyone else tried it to see if it's reproducible?

**Comment by mpatel31415** [comment] 2024-08-20 07:20
We see this error in recent runs as well. I'm able to reproduce it on 8xNVIDIA H100 80GB HBM3. Maybe you could try to add `--n_layers 1` flag to reduce memory usage? 
Here is the command I used with image from `20240814`
```
torchrun --standalone --max-restarts=0 --no-python --nproc-per-node=8 python /opt/pytorch/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py     --model_name Gemma-7b     --distributed_mode fsdp     --shard_mode zero2     --compile thunder_cudnn     --checkpoint_activations False     --low_precision_mode fp8-delayed-te     --micro_batch_size 1 --n_layers 1
```

**Comment by tfogal** [comment] 2024-08-21 16:29
> I'm able to reproduce it on 8xNVIDIA H100 80GB HBM3. Maybe you could try to add --n_layers 1 flag to reduce memory usage?

With `n_layers 1` can this reproduce with 1 GPU? probably easier to find 1 H100 rather than a whole node with 8.

**Comment by mpatel31415** [comment] 2024-08-22 10:18
Yes, the same error is present when running:
`python /opt/pytorch/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py --model_name Gemma-7b --compile thunder_cudnn --low_precision_mode fp8-delayed-te --micro_batch_size 1 --n_layers 1`

**Comment by IvanYashchuk** [comment] 2024-08-26 15:26
@kiya00, could you please take a look at this problem and tell what's needed for a fix?

**Comment by nvMelissa** [comment] 2024-08-26 18:13
Per triage meeting on 8/26, moved to @t-vi and assigned priority as P2.

**Comment by kiya00** [comment] 2024-08-29 14:46
It's strange that I still can't reproduce the error with image from 20240814:
<details> <summary>Full running log</summary>

```
wayan@viking-prod-229:~$ bash docker_run.sh yan1 gitlab-master.nvidia.com:5005/dl/pytorch/update-scripts:pjnl-20240814
+ docker run -d --gpus all --privileged --ipc=host -ti --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v /raid/dldata/:/data -v /mnt/nvdl/usr/wayan:/wayan --name yan1 gitlab-master.nvidia.com:5005/dl/pytorch/update-scripts:pjnl-20240814  
ec3676937091b22742c7754594bea1a83c929d771a7459db49910b3576e6ca01
+ docker exec -it yan1 /bin/bash
root@ec3676937091:/opt/pytorch/nvfuser# python /opt/pytorch/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py --model_name Gemma-7b --compile thunder_cudnn --low_precision_mode fp8-delayed-te --micro_batch_size 1 --n_layers 1
Loading model with {'name': 'Gemma-7b', 'hf_config': {'org': 'google', 'name': 'gemma-7b'}, 'scale_embeddings': True, 'block_size': 4096, 'vocab_size': 256000, 'padding_multiple': 64, 'padded_vocab_size': 256000, 'n_layer': 1, 'n_head': 16, 'head_size': 256, 'n_embd': 3072, 'rotary_percentage': 1.0, 'parallel_residual': False, 'bias': False, 'lm_head_bias': False, 'n_query_groups': 16, 'shared_attention_norm': False, 'norm_class_name': 'RMSNorm', 'norm_eps': 1e-05, 'mlp_class_name': 'GemmaMLP', 'gelu_approximate': 'tanh', 'intermediate_size': 24576, 'rope_condense_ratio': 1, 'rope_base': 10000, 'n_expert': 0, 'n_expert_per_token': 0, 'rope_n_elem': 256}
Time to instantiate model: 1.72 seconds.
/usr/local/lib/python3.10/dist-packages/lightning/fabric/utilities/throughput.py:299: mods argument is not needed anymore, you can stop passing it
iter 0: loss 13.1250, iter time: 10365.11ms, t: 4096
iter 1: loss 13.0000, iter time: 55.71ms, t: 4096
iter 2: loss 12.5625, iter time: 51.02ms, t: 4096
iter 3: loss 11.8125, iter time: 51.48ms, t: 4096
iter 4: loss 10.3750, iter time: 50.97ms, t: 4096
iter 5: loss 7.2500, iter time: 51.22ms, t: 4096
iter 6: loss 5.5938, iter time: 51.28ms, t: 4096
iter 7: loss 5.0938, iter time: 50.57ms, t: 4096
iter 8: loss 5.2188, iter time: 50.33ms, t: 4096
iter 9: loss 5.1875, iter time: 50.34ms, t: 4096
iter 10: loss 4.9375, iter time: 49.94ms, t: 4096
iter 11: loss 4.9688, iter time: 50.21ms, t: 4096
iter 12: loss 5.0000, iter time: 49.94ms, t: 4096
iter 13: loss 4.9062, iter time: 50.19ms, t: 4096
iter 14: loss 4.8750, iter time: 50.16ms, t: 4096
iter 15: loss 4.8750, iter time: 49.74ms, t: 4096
iter 16: loss 4.8750, iter time: 50.09ms, t: 4096
iter 17: loss 4.7812, iter time: 49.76ms, t: 4096
iter 18: loss 4.7500, iter time: 49.77ms, t: 4096
iter 19: loss 4.7500, iter time: 50.05ms, t: 4096
iter 20: loss 4.7812, iter time: 49.80ms, t: 4096
iter 21: loss 4.7500, iter time: 50.09ms, t: 4096
iter 22: loss 4.7500, iter time: 50.06ms, t: 4096
iter 23: loss 4.7188, iter time: 50.19ms, t: 4096
iter 24: loss 4.7500, iter time: 50.12ms, t: 4096
iter 25: loss 4.7188, iter time: 49.74ms, t: 4096
iter 26: loss 4.7500, iter time: 49.71ms, t: 4096
iter 27: loss 4.7188, iter time: 49.87ms, t: 4096
iter 28: loss 4.6875, iter time: 49.76ms, t: 4096
iter 29: loss 4.7188, iter time: 50.07ms, t: 4096
iter 30: loss 4.7188, iter time: 49.81ms, t: 4096
iter 31: loss 4.7188, iter time: 50.02ms, t: 4096
iter 32: loss 4.7188, iter time: 49.73ms, t: 4096
iter 33: loss 4.6875, iter time: 49.53ms, t: 4096
iter 34: loss 4.6875, iter time: 49.54ms, t: 4096
iter 35: loss 4.6875, iter time: 49.51ms, t: 4096
iter 36: loss 4.6875, iter time: 49.51ms, t: 4096
iter 37: loss 4.6875, iter time: 49.54ms, t: 4096
iter 38: loss 4.6875, iter time: 49.60ms, t: 4096
iter 39: loss 4.6875, iter time: 49.95ms, t: 4096
iter 40: loss 4.6562, iter time: 49.81ms, t: 4096
iter 41: loss 4.6875, iter time: 49.76ms, t: 4096
iter 42: loss 4.6875, iter time: 50.16ms, t: 4096
iter 43: loss 4.6562, iter time: 49.78ms, t: 4096
iter 44: loss 4.6875, iter time: 49.95ms, t: 4096
Model name: Gemma-7b
Seq Length: 4096
Micro BS: 1
Global BS: 1
Number of Layers: 1
Number of parameters: 1.85B
Distributed Mode: none
Compiler: thunder_cudnn_transformerengine
Low Precision Mode: fp8-delayed-te
Average iter time: 49.79 ms
Memory used: 23.09 GB
Tokens/s: 82255.19
Tokens/s/GPU: 82255.19
TFLOP/s: 541.31
root@ec3676937091:/opt/pytorch/nvfuser# torchrun --standalone --max-restarts=0 --no-python --nproc-per-node=8 python /opt/pytorch/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py     --model_name Gemma-7b     --distributed_mode fsdp     --shard_mode zero2     --compile thunder_cudnn     --checkpoint_activations False     --low_precision_mode fp8-delayed-te     --micro_batch_size 1 --n_layers 1
W0829 07:23:07.945000 733 torch/distributed/run.py:793]
W0829 07:23:07.945000 733 torch/distributed/run.py:793] *****************************************
W0829 07:23:07.945000 733 torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
W0829 07:23:07.945000 733 torch/distributed/run.py:793] *****************************************
Loading model with {'name': 'Gemma-7b', 'hf_config': {'org': 'google', 'name': 'gemma-7b'}, 'scale_embeddings': True, 'block_size': 4096, 'vocab_size': 256000, 'padding_multiple': 64, 'padded_vocab_size': 256000, 'n_layer': 1, 'n_head': 16, 'head_size': 256, 'n_embd': 3072, 'rotary_percentage': 1.0, 'parallel_residual': False, 'bias': False, 'lm_head_bias': False, 'n_query_groups': 16, 'shared_attention_norm': False, 'norm_class_name': 'RMSNorm', 'norm_eps': 1e-05, 'mlp_class_name': 'GemmaMLP', 'gelu_approximate': 'tanh', 'intermediate_size': 24576, 'rope_condense_ratio': 1, 'rope_base': 10000, 'n_expert': 0, 'n_expert_per_token': 0, 'rope_n_elem': 256}
Time to instantiate model: 0.00 seconds.
Loading model with {'name': 'Gemma-7b', 'hf_config': {'org': 'google', 'name': 'gemma-7b'}, 'scale_embeddings': True, 'block_size': 4096, 'vocab_size': 256000, 'padding_multiple': 64, 'padded_vocab_size': 256000, 'n_layer': 1, 'n_head': 16, 'head_size': 256, 'n_embd': 3072, 'rotary_percentage': 1.0, 'parallel_residual': False, 'bias': False, 'lm_head_bias': False, 'n_query_groups': 16, 'shared_attention_norm': False, 'norm_class_name': 'RMSNorm', 'norm_eps': 1e-05, 'mlp_class_name': 'GemmaMLP', 'gelu_approximate': 'tanh', 'intermediate_size': 24576, 'rope_condense_ratio': 1, 'rope_base': 10000, 'n_expert': 0, 'n_expert_per_token': 0, 'rope_n_elem': 256}
Time to instantiate model: 0.00 seconds.
Loading model with {'name': 'Gemma-7b', 'hf_config': {'org': 'google', 'name': 'gemma-7b'}, 'scale_embeddings': True, 'block_size': 4096, 'vocab_size': 256000, 'padding_multiple': 64, 'padded_vocab_size': 256000, 'n_layer': 1, 'n_head': 16, 'head_size': 256, 'n_embd': 3072, 'rotary_percentage': 1.0, 'parallel_residual': False, 'bias': False, 'lm_head_bias': False, 'n_query_groups': 16, 'shared_attention_norm': False, 'norm_class_name': 'RMSNorm', 'norm_eps': 1e-05, 'mlp_class_name': 'GemmaMLP', 'gelu_approximate': 'tanh', 'intermediate_size': 24576, 'rope_condense_ratio': 1, 'rope_base': 10000, 'n_expert': 0, 'n_expert_per_token': 0, 'rope_n_elem': 256}
Time to instantiate model: 0.00 seconds.
Loading model with {'name': 'Gemma-7b', 'hf_config': {'org': 'google', 'name': 'gemma-7b'}, 'scale_embeddings': True, 'block_size': 4096, 'vocab_size': 256000, 'padding_multiple': 64, 'padded_vocab_size': 256000, 'n_layer': 1, 'n_head': 16, 'head_size': 256, 'n_embd': 3072, 'rotary_percentage': 1.0, 'parallel_residual': False, 'bias': False, 'lm_head_bias': False, 'n_query_groups': 16, 'shared_attention_norm': False, 'norm_class_name': 'RMSNorm', 'norm_eps': 1e-05, 'mlp_class_name': 'GemmaMLP', 'gelu_approximate': 'tanh', 'intermediate_size': 24576, 'rope_condense_ratio': 1, 'rope_base': 10000, 'n_expert': 0, 'n_expert_per_token': 0, 'rope_n_elem': 256}
Time to instantiate model: 0.00 seconds.
Loading model with {'name': 'Gemma-7b', 'hf_config': {'org': 'google', 'name': 'gemma-7b'}, 'scale_embeddings': True, 'block_size': 4096, 'vocab_size': 256000, 'padding_multiple': 64, 'padded_vocab_size': 256000, 'n_layer': 1, 'n_head': 16, 'head_size': 256, 'n_embd': 3072, 'rotary_percentage': 1.0, 'parallel_residual': False, 'bias': False, 'lm_head_bias': False, 'n_query_groups': 16, 'shared_attention_norm': False, 'norm_class_name': 'RMSNorm', 'norm_eps': 1e-05, 'mlp_class_name': 'GemmaMLP', 'gelu_approximate': 'tanh', 'intermediate_size': 24576, 'rope_condense_ratio': 1, 'rope_base': 10000, 'n_expert': 0, 'n_expert_per_token': 0, 'rope_n_elem': 256}
Time to instantiate model: 0.01 seconds.
/usr/local/lib/python3.10/dist-packages/lightning/fabric/utilities/throughput.py:299: mods argument is not needed anymore, you can stop passing it
Loading model with {'name': 'Gemma-7b', 'hf_config': {'org': 'google', 'name': 'gemma-7b'}, 'scale_embeddings': True, 'block_size': 4096, 'vocab_size': 256000, 'padding_multiple': 64, 'padded_vocab_size': 256000, 'n_layer': 1, 'n_head': 16, 'head_size': 256, 'n_embd': 3072, 'rotary_percentage': 1.0, 'parallel_residual': False, 'bias': False, 'lm_head_bias': False, 'n_query_groups': 16, 'shared_attention_norm': False, 'norm_class_name': 'RMSNorm', 'norm_eps': 1e-05, 'mlp_class_name': 'GemmaMLP', 'gelu_approximate': 'tanh', 'intermediate_size': 24576, 'rope_condense_ratio': 1, 'rope_base': 10000, 'n_expert': 0, 'n_expert_per_token': 0, 'rope_n_elem': 256}
Time to instantiate model: 0.01 seconds.
Loading model with {'name': 'Gemma-7b', 'hf_config': {'org': 'google', 'name': 'gemma-7b'}, 'scale_embeddings': True, 'block_size': 4096, 'vocab_size': 256000, 'padding_multiple': 64, 'padded_vocab_size': 256000, 'n_layer': 1, 'n_head': 16, 'head_size': 256, 'n_embd': 3072, 'rotary_percentage': 1.0, 'parallel_residual': False, 'bias': False, 'lm_head_bias': False, 'n_query_groups': 16, 'shared_attention_norm': False, 'norm_class_name': 'RMSNorm', 'norm_eps': 1e-05, 'mlp_class_name': 'GemmaMLP', 'gelu_approximate': 'tanh', 'intermediate_size': 24576, 'rope_condense_ratio': 1, 'rope_base': 10000, 'n_expert': 0, 'n_expert_per_token': 0, 'rope_n_elem': 256}
Time to instantiate model: 0.00 seconds.
Loading model with {'name': 'Gemma-7b', 'hf_config': {'org': 'google', 'name': 'gemma-7b'}, 'scale_embeddings': True, 'block_size': 4096, 'vocab_size': 256000, 'padding_multiple': 64, 'padded_vocab_size': 256000, 'n_layer': 1, 'n_head': 16, 'head_size': 256, 'n_embd': 3072, 'rotary_percentage': 1.0, 'parallel_residual': False, 'bias': False, 'lm_head_bias': False, 'n_query_groups': 16, 'shared_attention_norm': False, 'norm_class_name': 'RMSNorm', 'norm_eps': 1e-05, 'mlp_class_name': 'GemmaMLP', 'gelu_approximate': 'tanh', 'intermediate_size': 24576, 'rope_condense_ratio': 1, 'rope_base': 10000, 'n_expert': 0, 'n_expert_per_token': 0, 'rope_n_elem': 256}
Time to instantiate model: 0.00 seconds.
iter 0: loss 13.0625, iter time: 26609.35ms, t: 4096
iter 1: loss 12.9375, iter time: 56.95ms, t: 4096
iter 2: loss 12.5000, iter time: 54.59ms, t: 4096
iter 3: loss 11.8125, iter time: 55.88ms, t: 4096
iter 4: loss 10.3125, iter time: 54.68ms, t: 4096
iter 5: loss 7.1250, iter time: 55.55ms, t: 4096
iter 6: loss 5.5312, iter time: 55.54ms, t: 4096
iter 7: loss 5.0312, iter time: 54.31ms, t: 4096
iter 8: loss 5.0938, iter time: 54.28ms, t: 4096
iter 9: loss 5.0000, iter time: 53.68ms, t: 4096
iter 10: loss 4.9062, iter time: 53.63ms, t: 4096
iter 11: loss 4.9062, iter time: 54.36ms, t: 4096
iter 12: loss 4.9375, iter time: 53.91ms, t: 4096
iter 13: loss 4.8750, iter time: 54.00ms, t: 4096
iter 14: loss 4.9062, iter time: 54.20ms, t: 4096
iter 15: loss 4.8438, iter time: 54.15ms, t: 4096
iter 16: loss 4.8438, iter time: 53.22ms, t: 4096
iter 17: loss 4.7500, iter time: 53.46ms, t: 4096
iter 18: loss 4.7812, iter time: 53.16ms, t: 4096
iter 19: loss 4.7812, iter time: 53.40ms, t: 4096
iter 20: loss 4.8125, iter time: 54.04ms, t: 4096
iter 21: loss 4.7812, iter time: 53.70ms, t: 4096
iter 22: loss 4.7188, iter time: 53.83ms, t: 4096
iter 23: loss 4.7500, iter time: 53.27ms, t: 4096
iter 24: loss 4.7500, iter time: 53.34ms, t: 4096
iter 25: loss 4.7188, iter time: 53.83ms, t: 4096
iter 26: loss 4.7188, iter time: 53.49ms, t: 4096
iter 27: loss 4.7188, iter time: 53.55ms, t: 4096
iter 28: loss 4.6875, iter time: 53.93ms, t: 4096
iter 29: loss 4.6875, iter time: 54.15ms, t: 4096
iter 30: loss 4.6875, iter time: 53.94ms, t: 4096
iter 31: loss 4.7188, iter time: 53.63ms, t: 4096
iter 32: loss 4.7188, iter time: 54.03ms, t: 4096
iter 33: loss 4.6875, iter time: 53.99ms, t: 4096
iter 34: loss 4.6875, iter time: 53.68ms, t: 4096
iter 35: loss 4.7188, iter time: 53.68ms, t: 4096
iter 36: loss 4.6875, iter time: 53.65ms, t: 4096
iter 37: loss 4.6875, iter time: 53.39ms, t: 4096
iter 38: loss 4.6875, iter time: 53.20ms, t: 4096
iter 39: loss 4.6875, iter time: 54.00ms, t: 4096
iter 40: loss 4.6875, iter time: 53.62ms, t: 4096
iter 41: loss 4.6875, iter time: 54.28ms, t: 4096
iter 42: loss 4.6875, iter time: 53.99ms, t: 4096
iter 43: loss 4.6875, iter time: 53.78ms, t: 4096
iter 44: loss 4.6875, iter time: 53.89ms, t: 4096
Model name: Gemma-7b
Seq Length: 4096
Micro BS: 1
Global BS: 8
Number of Layers: 1
Number of parameters: 0.23B
Distributed Mode: fsdp
Sharding Mode: zero2
Bucketing: none
Compiler: thunder_cudnn_transformerengine
Low Precision Mode: fp8-delayed-te
Average iter time: 53.81 ms
Memory used: 15.52 GB
Tokens/s: 608964.58
Tokens/s/GPU: 76120.57
TFLOP/s: 4007.51
```

</details>

**Comment by kiya00** [comment] 2024-09-03 13:28
A minimum reproduce is:
```
import torch, thunder
def fun(x):
    x = x * torch.tensor(0.5, dtype=x.dtype)
    return x
x = torch.randn((2,2),dtype=torch.bfloat16).cuda()
# print(fun(x))
jfun=thunder.jit(fun)
jfun(x)
```
Torch can run cuda tensor * cpu scalar tensor, but Thunder can't

**Comment by IvanYashchuk** [comment] 2024-09-06 13:27
The problem can also be fixed by modifying the LitGPT code here https://github.com/Lightning-AI/litgpt/blob/1d37f9a99bb4ba2b7373bc7fc5b8c5a457af48df/litgpt/model.py#L95
```diff
+ x = x * torch.tensor(self.config.n_embd**0.5, dtype=x.dtype, x.device)
- x = x * torch.tensor(self.config.n_embd**0.5, dtype=x.dtype)
```
2 months ago this line used a Python scalar and that's why it was working:
```py
x = x * (self.config.n_embd**0.5)
```

**Closed** 2024-09-10 18:25 UTC
Labels: triage review, mixology
